#!/bin/bash
# =============================================================
# fix-wsl2-network.sh
# Fixes Docker network connectivity issues in WSL2 environments.
#
# Problem: Docker tries to use IPv6 to reach docker.io but
#          IPv6 is not available → "network is unreachable"
#
# Run: bash scripts/fix-wsl2-network.sh
# Then: make build
# =============================================================

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}"
echo "  Pretexta — WSL2 Docker Network Fix"
echo "  ====================================${NC}"
echo ""

# Check if running in WSL
if ! grep -qi microsoft /proc/version 2>/dev/null; then
    echo -e "${YELLOW}Warning: This script is designed for WSL2.${NC}"
    echo "It may still work on other Linux systems with Docker."
    read -p "Continue? [y/N] " -n 1 -r
    echo
    [[ $REPLY =~ ^[Yy]$ ]] || exit 0
fi

echo -e "${CYAN}Step 1: Configure Docker daemon (force IPv4 DNS)${NC}"
sudo mkdir -p /etc/docker
cat <<'EOF' | sudo tee /etc/docker/daemon.json > /dev/null
{
    "dns": ["8.8.8.8", "8.8.4.4"],
    "ipv6": false,
    "max-concurrent-downloads": 3,
    "log-level": "warn"
}
EOF
echo -e "${GREEN}  /etc/docker/daemon.json written${NC}"

echo ""
echo -e "${CYAN}Step 2: Fix WSL2 DNS resolver${NC}"
# Check if resolv.conf is a symlink (auto-generated by WSL2)
if [ -L /etc/resolv.conf ]; then
    # Remove symlink and create a static file
    sudo rm /etc/resolv.conf
fi
printf 'nameserver 8.8.8.8\nnameserver 8.8.4.4\n' | sudo tee /etc/resolv.conf > /dev/null
echo -e "${GREEN}  /etc/resolv.conf updated${NC}"

echo ""
echo -e "${CYAN}Step 3: Prevent WSL2 from overwriting resolv.conf${NC}"
if ! grep -q "generateResolvConf = false" /etc/wsl.conf 2>/dev/null; then
    printf '\n[network]\ngenerateResolvConf = false\n' | sudo tee -a /etc/wsl.conf > /dev/null
    echo -e "${GREEN}  /etc/wsl.conf updated${NC}"
else
    echo -e "${GREEN}  /etc/wsl.conf already configured${NC}"
fi

echo ""
echo -e "${CYAN}Step 4: Restart Docker daemon${NC}"
if sudo service docker restart 2>/dev/null || sudo systemctl restart docker 2>/dev/null; then
    echo -e "${GREEN}  Docker restarted${NC}"
else
    echo -e "${YELLOW}  Could not auto-restart Docker. Restart manually.${NC}"
fi
sleep 3

echo ""
echo -e "${CYAN}Step 5: Test Docker connectivity${NC}"
if docker pull hello-world:latest > /dev/null 2>&1; then
    docker image rm hello-world:latest > /dev/null 2>&1 || true
    echo -e "${GREEN}  Docker can reach docker.io — network is FIXED!${NC}"
else
    echo -e "${RED}  Still failing. Try these additional steps:${NC}"
    echo ""
    echo "  From Windows (PowerShell as Admin):"
    echo "    wsl --shutdown"
    echo "    wsl"
    echo ""
    echo "  Or try restarting Docker Desktop if you're using it."
fi

echo ""
echo -e "${CYAN}Done!${NC} Now run: ${GREEN}make build${NC}"
echo ""
